steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      export DOCKER_BUILDKIT=1
      docker build -tgcr.io/alpine-fin-438723-d8/digi-visualizer:latest -f Dockerfile .
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/alpine-fin-438723-d8/digi-visualizer:latest']

